version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  standard:
    format: '%(asctime)s [%(levelname)s]  %(module)s.%(funcName)s(%(lineno)s) %(message)s'
  access:
    format: '%(asctime)s %(request_id)s %(request_method)s:%(request_path)s %(response_code)s EXECUTION_TIME=%(time_cost)s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: api_file.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8

  access_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: access
    filename: access.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8

root:
  level: DEBUG
  handlers: [console]

loggers:

  api_log:
    level: INFO
    handlers: [console, info_file_handler]
    propogate: no

  access_log:
    level: INFO
    handlers: [ console, access_file_handler ]
    propogate: no